"""rm jwt_token

Revision ID: 523077e9a7c7
Revises: d69699a80c37
Create Date: 2024-03-14 16:25:42.758506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523077e9a7c7'
down_revision: Union[str, None] = 'd69699a80c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
